# Generated by Django 3.2.9 on 2021-11-23 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(default='noimage2.png', upload_to='')),
            ],
        ),
    ]
